import type { Metadata } from "next";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { Sora } from "next/font/google";
import { Toaster } from "sonner";

import TopLoader from "@/components/top-loader";
import ReactQueryProvider from "@/providers/query-provider";

const sora = Sora({
	variable: "--font-sora",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sora.variable} antialiased`}>
				<TopLoader />
				<Toaster />
				<SessionProvider>
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
