version: '3.8'

services:
  aspnet-app:
    build:
      context: ./backend
    ports:
      - "5000:8080"
    depends_on:
      - ollama
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - AppSettings__Jwt__Secret=${JWT_SECRET}
      - AppSettings__Jwt__Issuer=${JWT_ISSUER}
      - AppSettings__Jwt__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - AppSettings__Jwt__Audience=${JWT_AUDIENCE}
      - AppSettings__GoogleClientID=${GOOGLE_CLIENT_ID}
    networks:
      - ollama-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-net
    environment:
      - OLLAMA_MODELS=llama3
    restart: unless-stopped

volumes:
  ollama-data:

networks:
  ollama-net:
